### first request
POST http://localhost:9191/producer/publish1
Content-Type: application/json

{
  "message": "Message send to the consumer by producer"
}


### second request
POST http://localhost:9191/producer/publish2
Content-Type: application/json

{
  "id" : 2,
  "name" : "Gaurav jangid",
  "age" : 29, 
  "email" : "gauravnjit2023@gmail.com"
}